name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Test
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run coverage-jenkins"

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: |
            ./coverage/