name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Test with coverage
        run: npm run coverage-jenkins

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: |
            ./coverage/

      - name: Save Code Linting Report JSON
        run: npm run lint:json
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v4
        continue-on-error: true
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./coverage/eslint-result.json"