name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'un-valor-para-que-no-de-error'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh ubuntu@${{ secrets.SSH_HOST }} "if [ ! -d 'nodeapp' ]; then \
              git clone https://github.com/pm161-ual/NodeJS.git; \
            else \
              cd NodeJS && git stash && git fetch --all && git reset --hard origin/main && git pull origin main; \
            fi"
          ssh ubuntu@${{ secrets.SSH_HOST }} "if pgrep node; then forever stopall; fi"
          ssh ubuntu@${{ secrets.SSH_HOST }} "cd NodeJS && npm install"
          ssh ubuntu@${{ secrets.SSH_HOST }} "cd NodeJS && forever start src/main.js"